compile:
	@echo "[Compiling Enigma...]"
	@g++ -std=c++11 -o enigma *.cpp
	@echo "[Complete]"

clean:
	@echo "[Cleaning directory]"
	@if test -f enigma ; then echo "[Removed executable]"; \
	rm enigma; \
	fi  
	@echo "[Complete]"

run:
	@echo "[Running Enigma...]"
	@./enigma
	@echo "[Closing Enigma]"
